# Generated by Django 4.1.2 on 2022-10-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20221026_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
